name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag syam:v1
    - name: Docker images list
      run: docker images
    - name: Docker tagging
      run: |
           docker images
           docker login -u ${{ secrets.docker_hub_username }} -p ${{ secrets.docker_hub_password }}
           docker push syamnarayan/github_action:v1
